name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    name: Back-end
    uses: ./.github/workflows/.github-ci.back.yml

  frontend:
    name: Front-end
    uses: ./.github/workflows/.github-ci.front.yml