name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build backend image
      run: docker build -t my-backend-image:latest -f back_student/Dockerfile .

    - name: Build frontend image
      run: docker build -t my-frontend-image:latest -f front_student/Dockerfile .

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.22.0_Linux-64bit.deb

    - name: Scan backend image with Trivy
      run: trivy image my-backend-image:latest

    - name: Scan frontend image with Trivy
      run: trivy image my-frontend-image:latest
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.22.0_Linux-64bit.deb

    - name: Scan backend image with Trivy and export report
      run: trivy image -o trivy-backend-report.txt my-backend-image:latest

    - name: Scan frontend image with Trivy and export report
      run: trivy image -o trivy-frontend-report.txt my-frontend-image:latest

    - name: Upload Trivy reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trivy-reports
        path: |
          trivy-backend-report.txt
          trivy-frontend-report.txt

    - name: Check for critical vulnerabilities in backend report
      id: check_backend
      run: |
        if grep -q '"Critical"' trivy-backend-report.txt; then
          echo "critical_found=true" >> $GITHUB_ENV
        else
          echo "critical_found=false" >> $GITHUB_ENV
        fi

    - name: Check for critical vulnerabilities in frontend report
      id: check_frontend
      run: |
        if grep -q '"Critical"' trivy-frontend-report.txt; then
          echo "critical_found=true" >> $GITHUB_ENV
        else
          echo "critical_found=false" >> $GITHUB_ENV
        fi

    - name: Decide deployment
      run: |
        if [ "$critical_found" == "true" ]; then
          echo "don't deploy critical vulnerabilities detected"
        else
          echo "you can deploy safely"
        fi
      env:
        critical_found: ${{ env.critical_found }}