stages:
  - build
  - test
  # - deploy

cache:
  paths:
    - front_student/node_modules
    - back_student/node_modules

include:
  - "/ops/gitlab/pipelines/.github-ci.back.yml"
  - "/ops/gitlab/pipelines/.github-ci.front.yml"
